# Generated by Django 6.0.6 on 2026-06-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(verbose_name='Introduction/Description')),
                ('contenu', models.TextField(verbose_name='Contenu textuel du cours (Markdown ou HTML)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question du quiz')),
                ('option1', models.CharField(max_length=255, verbose_name='Option A')),
                ('option2', models.CharField(max_length=255, verbose_name='Option B')),
                ('option3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option C')),
                ('option4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option D')),
                ('reponse_correcte', models.CharField(choices=[('1', 'Option A'), ('2', 'Option B'), ('3', 'Option C'), ('4', 'Option D')], max_length=10, verbose_name='Numéro de la bonne réponse')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.cours')),
            ],
        ),
    ]
