# Generated by Django 6.0.5 on 2026-05-20 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('DEB', 'Débutant'), ('INT', 'Intermédiaire'), ('AV', 'Avancé')], max_length=3)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('contenu_markdown', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequeteSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_analyse', models.CharField(default='Draft', max_length=100)),
                ('code_sql_initial', models.TextField()),
                ('code_sql_optimise', models.TextField(blank=True, null=True)),
                ('temps_execution_avant', models.FloatField(help_text='En millisecondes')),
                ('temps_execution_apres', models.FloatField(blank=True, help_text='En millisecondes', null=True)),
                ('score_efficience', models.IntegerField(default=0)),
                ('execution_plan_json', models.JSONField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommandationOptimisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Med'), ('HIGH', 'High')], max_length=10)),
                ('requete_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='labo_performance.requetesandbox')),
            ],
        ),
    ]
