# Generated by Django 6.0.6 on 2026-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('produit', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.FloatField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En cours', max_length=20)),
            ],
        ),
    ]
