# Generated by Django 4.2.30 on 2026-06-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_performance', '0002_commandetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
